### ISSUE TITLE
Windows 10: you cannot change tamper protection with reg.exe like you are doing

### ISSUE THREAD

**Issue by PhillipDScottJr** [TairikuOokami/Windows#1]
You cannot change the registry in the fashion you are implementing.  Maybe next time you will validate that your methods work instead of copying an pasting.  

this will not work:  
reg add "HKLM\Software\Microsoft\Windows Defender\Features" /v "TamperProtection" /t REG_DWORD /d "0" /f

**Comment by TairikuOokami** [comment]
I know it does not work, it is there for reference. I say to disable it manually at the beginning.
