### ISSUE TITLE
Weird behaviour when using this scripts

### ISSUE THREAD

**Issue by Noth-Shian** [TairikuOokami/Windows#10]
Hello, i'm another one having issues when using the "Windows Tweaks.bat" script...

My wifi got f up, i wasn't able to connect to any network
I fixed it by enabling some services like "Network Connections" "Network List Service" "Network Location Awareness" "WLAN Autoconfig" and etc

The computer name changed from "DESKTOP-LOLRNDM" to "FDDefine7Mini" i changed it to "H61M-K" later
But now i got this weird line on the about screen that says "Asrock AMD Radeon RX 6600 Challenger D 8GB" What the f...
![image](https://github.com/user-attachments/assets/b8d60723-3466-445b-9ee7-0f26f8617487)
I guess i can fix it by changing the OEM informating using a random software

The Win-key hotkeys stoped working... i can't Win+R, Win+D, Win+S, Win+., Win+V, etc
I can't type on any input spaces like this one
![image](https://github.com/user-attachments/assets/fc2f7c8d-9a02-492a-b44b-072074287abc)
I had to copy the password by Ctrl+C and then paste it by rightclick... How sad is that, i can't even Ctrl+V
And i think all of this is because the script deleted the "TIWorker.exe" or "ctfmon.exe" file... i think...
**I need to fix this man**

I had the same "A referral error was returned from the server" error another user had before
I fixed it by setting "ValidateAdminCodeSignatures" to 0 in regedit "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" 

Windows defender started blocking the scripts

The UAC was set to the highest setting posible

The "Folder Options" was changed to "Single click to open an item"

Now i have a cute screen saver

...

A lot of weird things man, why is all of this?
I think you should make a readme for dummies, it is a necessity
Or a script to revert this... Thx btw

**Comment by TairikuOokami** [comment]
As mentioned in Windows Tweaks - USE AT OWN RISK - Create a system backup to reverse any changes!

Radio Management Service (RmSvc) is required to be able to see and to connect to WiFi networks
Network List Service is required to be able to change Network Settings via old control panel

OEM settings are easily changeable

```
rem Support
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\OEMInformation" /v "Manufacturer" /t REG_SZ /d "TairikuOkami" /f
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\OEMInformation" /v "Model" /t REG_SZ /d "Asrock AMD Radeon RX 6600 Challenger D 8GB" /f
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\OEMInformation" /v "SupportHours" /t REG_SZ /d "Within 24-48 hours" /f
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\OEMInformation" /v "SupportPhone" /t REG_SZ /d "TairikuOkami@pm.me" /f
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\OEMInformation" /v "SupportURL" /t REG_SZ /d "https://www.elevenforum.com/members/tairikuokami.78" /f

rem Computer Description
reg add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "srvcomment" /t REG_SZ /d "500/100 MBps" /f

rem System info (Logo - 120x120.bmp)
rem shell:::{BB06C0E4-D293-4f75-8A90-CB05B6477EEE}
reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\OEMInformation" /v "Logo" /t REG_SZ /d "D:\OneDrive\Pictures\Logo.bmp" /f
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v "RegisteredOrganization" /t REG_SZ /d "(-_-)" /f
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v "RegisteredOwner" /t REG_SZ /d "Brony" /f
```

Windows keys are disabled, since those tweaks are also for gaming to avoid random presses. Still, Ctrl+C / Ctrl+V work for me and in store apps, since I use them, Defender must have blocked parts of the script, thus the reason I do not use it. ctfmon.exe can no longer be disabled, since it is required to login to Windows to type password/pin

Windows Clipboard is disabled to prevent malware/webpages/MS from stealing clipboard info.

Removing policies should remediate most changes and allow users to change settings at will.

```
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies" /f
reg delete "HKCU\Software\Policies" /f
reg delete "HKLM\Software\Microsoft\Policies" /f
reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies" /f
reg delete "HKLM\Software\Policies" /f
reg delete "HKLM\Software\WOW6432Node\Microsoft\Policies" /f
reg delete "HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Policies" /f
reg delete "HKLM\Software\WOW6432Node\Policies" /f
```
