### ISSUE TITLE
WinDefender disable.bat is not disabling webthreatdefsvc and its instances like webthreatdefusersvc!. everything else looks like disabled

### ISSUE THREAD

**Issue by skunkyall** [TairikuOokami/Windows#11]
it's not disabling webthreatdefsvc and its instances like webthreatdefusersvc!. everything else looks like disabled.

**Comment by skunkyall** [comment]
it's not disabling webthreatdefsvc and its instances like webthreatdefusersvc!. everything else looks like disabled.

**Comment by TairikuOokami** [comment]
Yes, because you can still use phishing protection just like SmartScreen without Defender, it is optional.

**Comment by kydex** [comment]
**TairikuOokami** Thank you for OPTIONAL code
