### ISSUE TITLE
Does Game Mode work with these tweaks?

### ISSUE THREAD

**Issue by g-k-m** [TairikuOokami/Windows#5]
![image](https://github.com/TairikuOokami/Windows/assets/37273303/a3cc295c-4c57-4f17-958e-71725b9781a5)

Since game bar and all that shit is disabled/deleted, does Game Mode still work? I read somewhere that gamebar is not required for game mode to work, and when using SpecialK, it identifies the power mode (different than power plan) as "Game mode", however i'm still not sure. Some people say game mode increases performance by a bit

**Comment by TairikuOokami** [comment]
No, but you can keep game mode by  not removing "GameBarPresenceWriter.exe" and enabling:
reg add "HKCU\Software\Microsoft\GameBar" /v "AutoGameModeEnabled" /t REG_DWORD /d "1" /f
Game mode works for some games (I would say store games) and not for others, you need to test it.
But I trust GPU manufacturers to optimize games via game profiles more than MS. It really depends.
