### ISSUE TITLE
EnableFullTrustStartupTasks / EnableUwpStartupTasks being set to 0 prevents users from automatically starting up MSIX apps

### ISSUE THREAD

**Issue by sylveon** [TairikuOokami/Windows#8]
The scripts in this repo currently set `EnableFullTrustStartupTasks` and `EnableUwpStartupTasks` to 0, which is causing problems for users who use apps through MSIX. Apps like
- TranslucentTB
- EarTrumpet
- New Teams

are affected, and cannot be enabled by the user to run at startup. When they try to do so from Task Manager, the app immediately flips back to being disabled. The burden of figuring out and resolving those issues is then left to the developers of those apps. I would recommend not setting this registry value and leaving it to the default.

**Comment by TairikuOokami** [comment]
Thanks for info. It is disabled to prevent any startup app, which could be abused by malware. Added the note on top.

**Comment by sylveon** [comment]
This doesn't really help against malware. These keys only affect packaged apps, and packaging an app requires signatures which ties back to a real world identity. As such, most malware is unpackaged and will use methods which aren't affected by those reg keys (the startup folder, Run registry key, scheduled tasks, etc.).

What typically happens, is that user run debloat script like this, forget about it, and then some months later will try to install/use one of those apps, and be dumbfounded that it doesn't work properly, making a bug report to the developer of the app.

**Comment by riverar** [comment]
EarTrumpet dev here. @sylveon is correct; this isn't a malware vector. Setting these values to `0` just breaks us legitimate indie apps. But if you don't wish to change this, _please_ provide a registry value somewhere that indicates the user ran one of your scripts. (Perhaps `HKEY_CURRENT_USER\Software\TairikuOkami!ScriptsRan=dword:0x1` or something similar. Then we can at least detect these machines in the wild when someone asks us for support. Thank you!
