### ISSUE TITLE
How do i get back my old windows

### ISSUE THREAD

**Issue by toodos** [TairikuOokami/Windows#9]
I ran this windowstweaks.bat and it fucked up my pc i hate this how to revert back

**Comment by toodos** [comment]
i cant run any fucking application because of this
![2024-09-12 09_54_17](https://github.com/user-attachments/assets/6b6ea06a-dffb-42ee-b318-768321573aea)

**Comment by TairikuOokami** [comment]
Restore a system image or change ValidateAdminCodeSignatures to 0

**Comment by toodos** [comment]
hey i updated my windows to 11 i thought that would fix it but no everthing is same and also only my browser has access to internet now and none other apps work they dont seem to get internet from my wifi but my browser gets like wtf is wrong with this mate

**Comment by toodos** [comment]
i was recommended by a guy on reddit

**Comment by super-lurker** [comment]
> > > hey i updated my windows to 11 i thought that would fix it but no everthing is same and also only my browser has access to internet now and none other apps work they dont seem to get internet from my wifi but my browser gets like wtf is wrong with this mate
> > 
> > 
> > that's what happens when you don't read and execute random script online.
> 
> thanks to you for putting a random ass script online without any read me

I didn't make this script, and SCRIPT is the read me. if you're new to this, I recommend the GUI version

**Comment by TairikuOokami** [comment]
> got that sorted i just changed my dns to google dns and it fix but help me when i open something in admin permission it asks me for password every single time help me with dat please

https://www.elevenforum.com/t/change-user-account-control-uac-settings-in-windows-11.1523

**Comment by toodos** [comment]
All good everything fixed just one last thing after i leave my pc on idle it logs me out how to fix that ?

**Comment by toodos** [comment]
Got that fixed thanks all fixed i just delete all the registries this app made now everything is back to normal thanks
